files = [ "xvme64x_core.vhd",
          "xvme64x_core_pkg.vhd",
          "VME64xCore_Top.vhd",
          "vme64x_pack.vhd",
          "VME_Access_Decode.vhd",
          "VME_Am_Match.vhd",
          "VME_bus.vhd",
          "VME_CR_CSR_Space.vhd",
          "VME_User_CSR.vhd",
          "VME_CRAM.vhd",
          "VME_Funct_Match.vhd",
          "VME_IRQ_Controller.vhd",
          "VME_swapper.vhd",
          "VME_Wb_master.vhd"]
